package c4container

import (
	"bytes"
	"context"
	errs "errors"
	"io"
	"net/http"
	"reflect"
	"strconv"
	"testing"

	"github.com/kislerdm/diagramastext/server/core/diagram"
	"github.com/kislerdm/diagramastext/server/core/errors"
)

func Test_compress(t *testing.T) {
	type args struct {
		v []byte
	}
	tests := []struct {
		name    string
		args    args
		want    []byte
		wantErr bool
	}{
		{
			name: "foo",
			args: args{
				v: []byte("foo"),
			},
			want:    []byte{75, 203, 207, 7, 0},
			wantErr: false,
		},
		{
			name: "foobar",
			args: args{
				v: []byte("foobar"),
			},
			want:    []byte{75, 203, 207, 79, 74, 44, 2, 0},
			wantErr: false,
		},
		{
			name: "@startuml",
			args: args{
				v: []byte(`@startuml`),
			},
			want:    []byte{115, 40, 46, 73, 44, 42, 41, 205, 205, 1, 0},
			wantErr: false,
		},
		{
			name: `foo
bar`,
			args: args{
				v: []byte(`foo
bar`),
			},
			want:    []byte{75, 203, 207, 231, 74, 74, 44, 2, 0},
			wantErr: false,
		},
		{
			name: "->",
			args: args{
				v: []byte(`->`),
			},
			want:    []byte{211, 181, 3, 0},
			wantErr: false,
		},
		{
			name: "a->b",
			args: args{
				v: []byte("a->b"),
			},
			want:    []byte{75, 212, 181, 75, 2, 0},
			wantErr: false,
		},
		{
			name: "a -> b",
			args: args{
				v: []byte("a -> b"),
			},
			want:    []byte{75, 84, 208, 181, 83, 72, 2, 0},
			wantErr: false,
		},
		{
			name: `@startuml
    a -> b
@enduml`,
			args: args{
				v: []byte(`@startuml
    a -> b
@enduml`),
			},
			want: []byte{
				115, 40, 46, 73, 44, 42, 41, 205, 205, 225, 82, 0, 130, 68, 5, 93, 59, 133, 36, 46, 135, 212, 188, 20,
				160, 16, 0,
			},
			wantErr: false,
		},
		{
			name: "unhappy path",
			args: args{
				v: []byte{0},
			},
			want:    nil,
			wantErr: true,
		},
	}

	t.Parallel()

	for _, tt := range tests {
		t.Run(
			tt.name, func(t *testing.T) {
				got, err := compress(tt.args.v)
				if (err != nil) != tt.wantErr {
					t.Errorf("compress() error = %v, want %v", err, tt.wantErr)
					return
				}
				if !reflect.DeepEqual(got, tt.want) {
					t.Errorf("compress() got = %v, want %v", got, tt.want)
				}
			},
		)
	}
}

func Test_encode6bit(t *testing.T) {
	type args struct {
		min, max, threshold byte
	}
	tests := []struct {
		name string
		args args
		want func(in byte, got byte) bool
	}{
		{
			name: "<10bite",
			args: args{0, 10, 48},
		},
		{
			name: "<36bite",
			args: args{10, 36, 65},
		},
		{
			name: "<62bite",
			args: args{36, 62, 97},
		},
		{
			name: "'-'",
			args: args{62, 62, '-'},
		},
		{
			name: "'_'",
			args: args{63, 63, '_'},
		},
		{
			name: "'?'",
			args: args{64, 64, '?'},
		},
	}
	t.Parallel()
	for _, tt := range tests {
		t.Run(
			tt.name, func(t *testing.T) {
				for i := tt.args.min; i < tt.args.max; i++ {
					got := encode6bit(i)
					want := tt.args.threshold + i - tt.args.min
					if got != want {
						t.Errorf("encode6bit(%v) unexpected result. got = %v, want = %v", i, got, want)
						return
					}
				}
			},
		)
	}

	// syntax signs

}

func Test_encode64(t *testing.T) {
	type args struct {
		e []byte
	}
	tests := []struct {
		name string
		args args
		want string
	}{
		{
			name: "len(e)==2",
			args: args{
				e: []byte{0, 0},
			},
			want: "0000",
		},
		{
			name: "len(e)==1",
			args: args{
				e: []byte{0},
			},
			want: "0000",
		},
		{
			name: "len(e)==3",
			args: args{
				e: []byte{0, 0, 0},
			},
			want: "0000",
		},
	}

	t.Parallel()

	for _, tt := range tests {
		t.Run(
			tt.name, func(t *testing.T) {
				if got := encode64(tt.args.e); got != tt.want {
					t.Errorf("encode64() = %v, want %v", got, tt.want)
				}
			},
		)
	}
}

func Test_marshal(t *testing.T) {
	type args struct {
		c *c4ContainersGraph
	}
	tests := []struct {
		name    string
		args    args
		want    []byte
		wantErr error
	}{
		{
			name: "simple diagram",
			args: args{
				c: &c4ContainersGraph{
					Containers: []*container{{ID: "0"}},
				},
			},
			want: []byte(`@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
footer "generated by diagramastext.dev - %date('yyyy-MM-dd')"
Container(0, "0")
@enduml`),
			wantErr: nil,
		},
		{
			name: "extended diagram",
			args: args{
				c: &c4ContainersGraph{
					Containers: []*container{
						{
							ID:     "0",
							Label:  "User",
							IsUser: true,
						},
						{
							ID:          "1",
							Label:       "Single-Page App",
							Technology:  "JavaScript",
							Description: "The main interface that the user interacts with",
							System:      "Web Client",
						},
						{
							ID:          "2",
							Label:       "Web Application",
							Technology:  "GitHub Pages",
							Description: "Delivers the static content and the diagramastext.dev SPA",
							System:      "Web Client",
							IsExternal:  true,
						},
						{
							ID:          "3",
							Label:       "Generate diagram",
							Technology:  "Go, GCP CloudRun",
							Description: "Handles all logic",
							System:      "Core",
						},
						{
							ID:          "4",
							Label:       "Access Credentials",
							Technology:  "GCP Secretsmanager",
							Description: "Stores access credentials for the Database and OpenAI",
							System:      "Core",
						},
						{
							ID:          "5",
							Label:       "Database",
							Technology:  "Postgres, Neon Platform",
							Description: "Stores user's prompts and model's prediction results",
							IsDatabase:  true,
						},
					},
					Rels: []*rel{
						{
							From:       "0",
							To:         "1",
							Label:      "Uses",
							Technology: "HTTPS",
						},
						{
							From:  "2",
							To:    "1",
							Label: "Delivers",
						},
						{
							From:       "1",
							To:         "3",
							Label:      "Uses",
							Technology: "async, JSON/HTTPS",
						},
						{
							From:       "3",
							To:         "4",
							Label:      "Uses",
							Direction:  "RL",
							Technology: "async, JSON/HTTPS",
						},
						{
							From:       "3",
							To:         "5",
							Label:      "Uses",
							Direction:  "TD",
							Technology: "sync, Go driver",
						},
					},
					Title: "Container diagram for diagramastext.dev",
					Footer: `  foobar
"bazqux
quxx"  `,
					WithLegend: true,
				},
			},
			want: []byte(`@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
footer "foobar\n"bazqux\nquxx""
title "Container diagram for diagramastext.dev"
Person(0, "User")
ContainerDb(5, "Database", "Postgres, Neon Platform", "Stores user's prompts and model's prediction results")
System_Boundary(WebClient, "Web Client") {
Container(1, "Single-Page App", "JavaScript", "The main interface that the user interacts with")
Container_Ext(2, "Web Application", "GitHub Pages", "Delivers the static content and the diagramastext.dev SPA")
}
System_Boundary(Core, "Core") {
Container(3, "Generate diagram", "Go, GCP CloudRun", "Handles all logic")
Container(4, "Access Credentials", "GCP Secretsmanager", "Stores access credentials for the Database and OpenAI")
}
Rel(0, 1, "Uses", "HTTPS")
Rel(2, 1, "Delivers")
Rel(1, 3, "Uses", "async, JSON/HTTPS")
Rel_L(3, 4, "Uses", "async, JSON/HTTPS")
Rel_D(3, 5, "Uses", "sync, Go driver")
SHOW_LEGEND()
@enduml`),
			wantErr: nil,
		},
		{
			name:    "unhappy path: no containers present in the graph",
			args:    args{c: &c4ContainersGraph{}},
			want:    nil,
			wantErr: errors.New("no containers found"),
		},
		{
			name: "unhappy path: container does not have ID",
			args: args{
				c: &c4ContainersGraph{
					Containers: []*container{{}},
				},
			},
			want:    nil,
			wantErr: errors.New("container must be identified: 'id' attribute"),
		},
		{
			name: "unhappy path: faulty relation",
			args: args{
				c: &c4ContainersGraph{
					Containers: []*container{{ID: "0"}, {ID: "1"}},
					Rels:       []*rel{{}},
				},
			},
			want:    nil,
			wantErr: errors.New("relation must specify the end nodes: 'from' and 'to' attributes"),
		},
	}

	t.Parallel()

	for _, tt := range tests {
		t.Run(
			tt.name, func(t *testing.T) {
				got, err := marshal(tt.args.c)
				if !reflect.DeepEqual(err, tt.wantErr) {
					t.Errorf("marshal() error = %v, want %v", err, tt.wantErr)
					return
				}
				if !reflect.DeepEqual(got, tt.want) {
					t.Errorf("marshal() got = %v, want %v", got, tt.want)
				}
			},
		)
	}
}

func Test_plantUMLRequest(t *testing.T) {
	type args struct {
		v []byte
	}
	tests := []struct {
		name    string
		args    args
		want    string
		wantErr bool
	}{
		{
			name: `@startuml
    a -> b
@enduml`,
			args: args{
				v: []byte(`@startuml
    a -> b
@enduml`),
			},
			want:    "SoWkIImgAStDuL80WaG5NJk592w7rBmKe100",
			wantErr: false,
		},
	}
	for _, tt := range tests {
		t.Run(
			tt.name, func(t *testing.T) {
				got, err := plantUMLRequest(tt.args.v)
				if (err != nil) != tt.wantErr {
					t.Errorf("plantUMLRequest() error = %v, want %v", err, tt.wantErr)
					return
				}
				if got != tt.want {
					t.Errorf("plantUMLRequest() got = %v, want %v", got, tt.want)
				}
			},
		)
	}
}

func Test_renderDiagramHappyPath(t *testing.T) {
	t.Parallel()

	t.Run(
		"happy path", func(t *testing.T) {
			// GIVEN
			want := []byte(`<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" contentStyleType="text/css" height="351px" preserveAspectRatio="none" style="width:258px;height:351px;background:#FFFFFF;" version="1.1" viewBox="0 0 258 351" width="258px" zoomAndPan="magnify"><defs/><g><!--entity 0--><g id="elem_0"><rect fill="#08427B" height="86.625" rx="2.5" ry="2.5" style="stroke:#073B6F;stroke-width:0.5;" width="68" x="97" y="7"/><image height="48" width="48" x="107" xlink:href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAIAAADYYG7QAAACD0lEQVR4Xu2YoU4EMRCGT+4j8Ai8AhaH4QHgAUjQuFMECUgMIUgwJAgMhgQsAYUiJCiQIBBY+EITsjfTdme6V24v4c8vyGbb+ZjOtN0bNcvjQXmkH83WvYBWto6PLm6v7p7uH1/w2fXD+PBycX1Pv2l3IdDm/vn7x+dXQiAubRzoURa7gRZWd0iGRIiJbOnhnfYBQZNJjNbuyY2eJG8fkDE3bbG4ep6MHUAsgYxmE3nVs6VsBWJSGccsOlFPmLIViMzLOB7pCVO2AtHJMohH7Fh6zqitQK7m0rJvAVYgGcEpe//PLdDz65sM4pF9N7ICcXDKIB5Nv6j7tD0NoSdM2QrU9Gg0ewE1LqBhHR3BBdvj2vapnidjHxD/q6vd7Pvhr31AwcY8eXMTXAKECZZJFXuEq27aLgQK5uLMohCenGGuGewOxSjBvYBqeG6B+Nqiblggdjnc+ZXDy+FNFpFzw76O3UBAROuXh6FoiAcf5g9eTvUgzy0nWg6I8cXHRUpg5bOVBCo+KDpFajOf23GgPme7RSQ+lacIENUgJ6gg1k6HjgOlqnLqip4tEuhv0hNEMXUD0clyXE3p6pZA0S2nnvTlXwLJEZWlb7cTQH1+USgTN4VhAenm/wea1OCAOmqo6fE1WCb9WSKBah+rbUWPWAmE2Rvk0ApiB45eOyNAzU8xcTvj8KvkKEoOaIYeHNA3ZuygAvFMUO0AAAAASUVORK5CYII=" y="17"/><text fill="#FFFFFF" font-family="sans-serif" font-size="16" font-weight="bold" lengthAdjust="spacing" textLength="45" x="108.5" y="79.8516">Anna</text></g><!--entity 1--><g id="elem_1"><rect fill="#08427B" height="86.625" rx="2.5" ry="2.5" style="stroke:#073B6F;stroke-width:0.5;" width="68" x="97" y="169"/><image height="48" width="48" x="107" xlink:href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAIAAADYYG7QAAACD0lEQVR4Xu2YoU4EMRCGT+4j8Ai8AhaH4QHgAUjQuFMECUgMIUgwJAgMhgQsAYUiJCiQIBBY+EITsjfTdme6V24v4c8vyGbb+ZjOtN0bNcvjQXmkH83WvYBWto6PLm6v7p7uH1/w2fXD+PBycX1Pv2l3IdDm/vn7x+dXQiAubRzoURa7gRZWd0iGRIiJbOnhnfYBQZNJjNbuyY2eJG8fkDE3bbG4ep6MHUAsgYxmE3nVs6VsBWJSGccsOlFPmLIViMzLOB7pCVO2AtHJMohH7Fh6zqitQK7m0rJvAVYgGcEpe//PLdDz65sM4pF9N7ICcXDKIB5Nv6j7tD0NoSdM2QrU9Gg0ewE1LqBhHR3BBdvj2vapnidjHxD/q6vd7Pvhr31AwcY8eXMTXAKECZZJFXuEq27aLgQK5uLMohCenGGuGewOxSjBvYBqeG6B+Nqiblggdjnc+ZXDy+FNFpFzw76O3UBAROuXh6FoiAcf5g9eTvUgzy0nWg6I8cXHRUpg5bOVBCo+KDpFajOf23GgPme7RSQ+lacIENUgJ6gg1k6HjgOlqnLqip4tEuhv0hNEMXUD0clyXE3p6pZA0S2nnvTlXwLJEZWlb7cTQH1+USgTN4VhAenm/wea1OCAOmqo6fE1WCb9WSKBah+rbUWPWAmE2Rvk0ApiB45eOyNAzU8xcTvj8KvkKEoOaIYeHNA3ZuygAvFMUO0AAAAASUVORK5CYII=" y="179"/><text fill="#FFFFFF" font-family="sans-serif" font-size="16" font-weight="bold" lengthAdjust="spacing" textLength="35" x="113.5" y="241.8516">Bob</text></g><!--link 0 to 1--><g id="link_0_1"><path d="M131,94.377 C131,114.815 131,139.407 131,160.7686 " fill="none" id="0-to-1" style="stroke:#666666;stroke-width:1.0;"/><polygon fill="#666666" points="131,168.7822,134,160.7822,128,160.7822,131,168.7822" style="stroke:#666666;stroke-width:1.0;"/><text fill="#666666" font-family="sans-serif" font-size="12" font-weight="bold" lengthAdjust="spacing" textLength="34" x="132" y="136.1387">Calls</text></g><rect fill="none" height="16.2969" style="stroke:none;stroke-width:1.0;" width="94" x="78" y="279.625"/><text fill="#000000" font-family="sans-serif" font-size="14" font-weight="bold" lengthAdjust="spacing" textLength="57" x="78" y="292.6201">Legend</text><text fill="#FFFFFF" font-family="sans-serif" font-size="14" lengthAdjust="spacing" textLength="4" x="135" y="292.6201">&nbsp;</text><rect fill="#08427B" height="16.2969" style="stroke:none;stroke-width:1.0;" width="94" x="78" y="295.9219"/><text fill="#073B6F" font-family="sans-serif" font-size="14" lengthAdjust="spacing" textLength="8" x="82" y="308.917">▯</text><text fill="#FFFFFF" font-family="sans-serif" font-size="14" lengthAdjust="spacing" textLength="4" x="90" y="308.917">&nbsp;</text><image height="12" width="12" x="94" xlink:href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMCAIAAADZF8uwAAAAjUlEQVR4XmPgcKpGRtGNy/0qFqIJMiBz/iMB7IpOXXuErGjK2mNYFH3/+RtZ0d6zd7Aoim9ZiaxIN64fiyIg6liyH6IivnUlsjhCkWpkt1nqZAjbLnuGbFAbuiJki+AA6EqEoq3HbqDLw0DLwr1QRegySODW49dQRb///EWXhIFT1x4j3GSYNBErgsgCADsg9+PJKhUuAAAAAElFTkSuQmCC" y="300.2188"/><text fill="#FFFFFF" font-family="sans-serif" font-size="14" lengthAdjust="spacing" textLength="50" x="114" y="308.917">person</text><text fill="#FFFFFF" font-family="sans-serif" font-size="14" lengthAdjust="spacing" textLength="4" x="168" y="308.917">&nbsp;</text><line style="stroke:none;stroke-width:1.0;" x1="78" x2="172" y1="279.625" y2="279.625"/><line style="stroke:none;stroke-width:1.0;" x1="78" x2="172" y1="295.9219" y2="295.9219"/><line style="stroke:none;stroke-width:1.0;" x1="78" x2="172" y1="312.2188" y2="312.2188"/><line style="stroke:none;stroke-width:1.0;" x1="78" x2="78" y1="279.625" y2="312.2188"/><line style="stroke:none;stroke-width:1.0;" x1="172" x2="172" y1="279.625" y2="312.2188"/><text fill="#888888" font-family="sans-serif" font-size="10" lengthAdjust="spacing" textLength="250" x="0" y="341.501">generated by diagramastext.dev - 2023-03-18</text><!--SRC=[DSj1Yy8m48RXkxyYMn1RC8t2dhnf5JrOLrp4eqoRiGRIf2HJNV-zKs7d-BppVHbNsrwZk1DrSQ5KW6VU6BhtLHynrDuHEifhtwhEWgE-jJAIjgPInRSy3dGkzwg5I1YOhWKlm3WCUSU_evlt74JI81CGQb6zX3RG1FXi_YZN-11IZ3NNTFBYasKfjPvaoUY88NgNpgOYMJe7IVOlSvQLhnXEQ8S-G07MHgRVtS_bkjziDuTrchq1]--></g></svg>`)

			httpClient := diagram.MockHTTPClient{
				V: &http.Response{
					Body:       io.NopCloser(bytes.NewReader(want)),
					StatusCode: http.StatusOK,
				},
			}

			graph := &c4ContainersGraph{
				Containers: []*container{
					{
						ID:     "0",
						Label:  "Anna",
						IsUser: true,
					},
					{
						ID:     "1",
						Label:  "Bob",
						IsUser: true,
					},
				},
				Rels: []*rel{
					{
						From:  "0",
						To:    "1",
						Label: "Calls",
					},
				},
				WithLegend: true,
			}

			// WHEN
			got, err := renderDiagram(context.TODO(), httpClient, graph)

			// THEN
			if err != nil {
				t.Fatal(err)
			}

			if !reflect.DeepEqual(got, want) {
				t.Fatalf("unexpected result. got: %+v, want: %+v", got, want)
			}
		},
	)
}

func Test_renderDiagramUnhappyPath(t *testing.T) {
	type args struct {
		ctx        context.Context
		httpClient diagram.HTTPClient
		v          *c4ContainersGraph
	}
	tests := []struct {
		name        string
		args        args
		wantErrText string
	}{
		{
			name: "no nodes",
			args: args{
				ctx: context.TODO(),
				v:   &c4ContainersGraph{},
			},
			wantErrText: "diagram/c4container/plantuml.go:64: no containers found",
		},
		{
			name: "http call error",
			args: args{
				ctx: context.TODO(),
				httpClient: diagram.MockHTTPClient{
					Err: errs.New("foobar"),
				},
				v: &c4ContainersGraph{Containers: []*container{{ID: "0"}}},
			},
			wantErrText: "diagram/c4container/plantuml.go:41: foobar",
		},
		{
			name: "http response not OK",
			args: args{
				ctx: context.TODO(),
				httpClient: diagram.MockHTTPClient{
					V: &http.Response{
						StatusCode: http.StatusTooManyRequests,
					},
				},
				v: &c4ContainersGraph{Containers: []*container{{ID: "0"}}},
			},
			wantErrText: "diagram/c4container/plantuml.go:46: the response is not ok, status code: " + strconv.Itoa(http.StatusTooManyRequests),
		},
	}
	for _, tt := range tests {
		t.Run(
			tt.name, func(t *testing.T) {
				if _, err := renderDiagram(tt.args.ctx, tt.args.httpClient, tt.args.v); !errors.IsError(
					err, tt.wantErrText,
				) {
					t.Errorf("renderDiagram() error = %v, want = %s", err, tt.wantErrText)
					return
				}
			},
		)
	}
}

func Test_dslContainerType(t *testing.T) {
	type args struct {
		o *bytes.Buffer
		n *container
	}
	tests := []struct {
		name string
		args args
		want string
	}{
		{
			name: "person",
			args: args{
				o: &bytes.Buffer{},
				n: &container{ID: "0", IsUser: true},
			},
			want: "Person",
		},
		{
			name: "person, external",
			args: args{
				o: &bytes.Buffer{},
				n: &container{ID: "0", IsUser: true, IsExternal: true},
			},
			want: "Person_Ext",
		},
		{
			name: "container",
			args: args{
				o: &bytes.Buffer{},
				n: &container{ID: "0"},
			},
			want: "Container",
		},
		{
			name: "container, external",
			args: args{
				o: &bytes.Buffer{},
				n: &container{ID: "0", IsExternal: true},
			},
			want: "Container_Ext",
		},
		{
			name: "container, external",
			args: args{
				o: &bytes.Buffer{},
				n: &container{ID: "0", IsExternal: true},
			},
			want: "Container_Ext",
		},
		{
			name: "queue",
			args: args{
				o: &bytes.Buffer{},
				n: &container{ID: "0", IsQueue: true},
			},
			want: "ContainerQueue",
		},
		{
			name: "queue, external",
			args: args{
				o: &bytes.Buffer{},
				n: &container{ID: "0", IsQueue: true, IsExternal: true},
			},
			want: "ContainerQueue_Ext",
		},
		{
			name: "db",
			args: args{
				o: &bytes.Buffer{},
				n: &container{ID: "0", IsDatabase: true},
			},
			want: "ContainerDb",
		},
		{
			name: "db, external",
			args: args{
				o: &bytes.Buffer{},
				n: &container{ID: "0", IsDatabase: true, IsExternal: true},
			},
			want: "ContainerDb_Ext",
		},
	}

	t.Parallel()

	for _, tt := range tests {
		t.Run(
			tt.name, func(t *testing.T) {
				dslContainerType(tt.args.o, tt.args.n)
				if tt.args.o.String() != tt.want {
					t.Fatalf("unexpected results. got: %s, want: %s", tt.args.o.String(), tt.want)
				}
			},
		)
	}
}

func Test_relationDirection(t *testing.T) {
	type args struct {
		s string
	}
	tests := []struct {
		name string
		args args
		want string
	}{
		{
			name: "default",
			args: args{},
			want: "",
		},
		{
			name: "left-right",
			args: args{"LR"},
			want: "R",
		},
		{
			name: "right-left",
			args: args{"RL"},
			want: "L",
		},
		{
			name: "top-down",
			args: args{"TD"},
			want: "D",
		},
		{
			name: "down-top",
			args: args{"DT"},
			want: "U",
		},
	}
	for _, tt := range tests {
		t.Run(
			tt.name, func(t *testing.T) {
				if got := relationDirection(tt.args.s); got != tt.want {
					t.Errorf("relationDirection() = %v, want %v", got, tt.want)
				}
			},
		)
	}
}
